[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/l/*"
  to = "/api/redirect/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
